### ISSUE TITLE
always response "404: Not Found"

### ISSUE THREAD

**Issue by rik43** [DevAlone/proxy_py#3]
i'm try to run your virtual box build. 
server always return string "404: Not Found"

php code example:
```
<?php

$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'http://127.0.0.1:55555/api/v1/');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, '{"model": "proxy", "method": "get"}');
curl_setopt($ch, CURLOPT_POST, 1);

curl_setopt($ch, CURLOPT_HTTPHEADER, [
    'Content-Type: application/json'
]);

$result = curl_exec($ch);

echo $result;
```
ports forwarding ok.

**Comment by DevAlone** [comment]
Virtualbox build has a very old version of proxy_py, afair, url on this version should be 'http://127.0.0.1:55555/api/'. 

But I'd recommend you to use the latest version from a docker container https://github.com/DevAlone/proxy_py#how-to-install

**Comment by rik43** [comment]
yes 'http://127.0.0.1:55555' its works, thanx. 
i'm try docker later.
