### ISSUE TITLE
Implement determining location of proxies

### ISSUE THREAD

**Issue by DevAlone** [DevAlone/proxy_py#4]
Now proxy_py lacks this feature because collectors which support locations are very slow. So, the idea is to use a public IP:Location database. Maxmind's https://github.com/maxmind/GeoIP2-python seems to be fine. 

What you need to do:

0. add an option `GEOLITE2_CITY_FILE_LOCATION` in `_settings.py` in new section, which should has default value `/tmp/proxy_py_9910549a_7d41_4102_9e9d_15d39418a5cb/GeoLite2-City.mmdb`(just a random uuid to not break any other software storing its files in tmp). 
1. Remove fields `city`, `region` and `country_code` and their indices from Proxy model https://github.com/DevAlone/proxy_py/blob/master/models.py
2. Remove code touching these fields https://github.com/DevAlone/proxy_py/blob/master/processor.py#L361
3. Add new property `location` to Proxy model which will make a request to maxmind's database stored in GEOLITE2_CITY_FILE_LOCATION and will return a dictionary with fields `latitude`, `longitude`, `country_code`, `country`, `city`. Don't forget to check if the database was initialized successfully(file exists) and log a warning otherwise. 
4. Remove fields `city`, `region` and `country_code` from server's config https://github.com/DevAlone/proxy_py/blob/master/proxy_py/_settings.py#L82 and add field location there
5. Check that everything works fine

**Comment by s0d3s** [comment]
Let`s do it)
