### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by qubiq1337** [DevAlone/proxy_py#6]
Hi. 
I build and run project from docker-image, however, when i am trying to fetch proxy list by API i get 500 Internal Server Error.
I got something like this in console:
```
ERROR ~ [proxy_py/server] ~ 2020-02-03 09:58:48,802 ~                            log():L57 - Your reverse proxy doesn't present user's IP.
```
I am tryed different network connections.
How to fix that?

**Comment by Qubiq1337** [comment]
So, this error occurs only if I try to get a large number of proxies(>600).
```
curl -X POST http://127.0.0.1:55555/api/v1/ -H "Content-Type: application/json" --data '{"model": "proxy", "method": "get", "limit": 1}'
{"status":"OK" ...}

curl -X POST http://127.0.0.1:55555/api/v1/ -H "Content-Type: application/json" --data '{"model": "proxy", "method": "get", "limit": 600}'
Server error
```
Howewer its around 32000 proxyes avaliable.
```
curl -X POST http://127.0.0.1:55555/api/v1/ -H "Content-Type: application/json" --data '{"model": "proxy", "method": "count"}'
{"status": "ok", "count": 32301, "status_code": 200}
```

**Comment by Qubiq1337** [comment]
proxy_py=# select count(*) from proxies;
 count 
-------
 39001
(1 row)

**Comment by DevAlone** [comment]
The error is saying that, for some reason, there is no such IP in geo database. As a workaround, you can try to request specific fields like this:
```curl -v -X POST https://proxy.d3d.info/api/v1/ --data '{"method": "get", "model": "proxy", "limit": 1, "fields": "address,response_time"}
```
without `location` field. Probably it will do the trick. 

Thanks for the issue, I will fix it at some point.

**Comment by DevAlone** [comment]
The error is saying that, for some reason, there is no such IP in geo database. As a workaround, you can try to request specific fields like this:
```
curl -v -X POST https://localhost:55555/api/v1/ --data '{"method": "get", "model": "proxy", "limit": 1, "fields": "address,response_time"}
```
without `location` field. Probably it will do the trick. 

Thanks for the issue, I will fix it at some point.
