### ISSUE TITLE
Collector gatherproxy broke

### ISSUE THREAD

**Issue by DevAlone** [DevAlone/proxy_py#7]
https://github.com/DevAlone/proxy_py/blob/master/collectors/web/com/gatherproxy/collector.py

maybe because they've changed domain

**Comment by expm2020** [comment]
the proxy selection template from the page has changed

        matches = re.findall(
#            r"document\.write\('([0-9.]+)'\).+?document\.write\(gp\.dep\('(.+?)'\)\)",
            r"\"PROXY_IP\":\"([0-9.]+)\".+?\"PROXY_PORT\":\"(.+?)\"",
            table_text, re.DOTALL
        )

Parsing occurs from only one page, did pagination work at all?

**Comment by DevAlone** [comment]
Site is not available and collector was deleted
