### ISSUE TITLE
Postgresql 50% cpu usage 

### ISSUE THREAD

**Issue by FeeeeK** [DevAlone/proxy_py#9]
![image](https://user-images.githubusercontent.com/26704473/79857988-52e26f00-83d7-11ea-8c95-f19f2452c216.png)
Is there any way to fix this?

**Comment by DevAlone** [comment]
Why do you think it's a bug?

**Comment by FeeeeK** [comment]
If this is not a bug, what can be done about it?

**Comment by DevAlone** [comment]
I think nothing. It's normal when postgres uses CPU

**Comment by FeeeeK** [comment]
ОК, thanks.
